//! Design-token values GENERATED by `cargo xtask gen-tokens` — do not edit
//! by hand.
//!
//! Source of truth: the `ui-tokens` crate shared with the Direct2D desktop
//! face in Rust-DeskApp. This crate never depends on it (it is consumed as a
//! git dependency, where that sibling path does not exist): the generator
//! reads the real values and writes them here, and `cargo xtask verify`
//! fails when this file drifts (`gen-tokens --check`). Edit the tokens
//! upstream, re-run the generator, and commit the result.
//!
//! Dimensions are DIPs (1 DIP = 1 CSS px at a 16px root); colours are packed
//! `0x00RRGGBB`.

/// Motion: durations in milliseconds, and easing curves as cubic-bezier
/// control points `(x1, y1, x2, y2)`.
pub mod motion {
    /// `ui_tokens::motion::DURATION_FAST_MS`.
    pub const DURATION_FAST_MS: u32 = 83;
    /// `ui_tokens::motion::DURATION_NORMAL_MS`.
    pub const DURATION_NORMAL_MS: u32 = 200;
    /// `ui_tokens::motion::DURATION_SLOW_MS`.
    pub const DURATION_SLOW_MS: u32 = 300;
    /// `ui_tokens::motion::Easing::Linear.bezier()`.
    pub const EASE_LINEAR: (f32, f32, f32, f32) = (0.0, 0.0, 1.0, 1.0);
    /// `ui_tokens::motion::Easing::Standard.bezier()`.
    pub const EASE_STANDARD: (f32, f32, f32, f32) = (0.33, 0.0, 0.67, 1.0);
    /// `ui_tokens::motion::Easing::Decelerate.bezier()`.
    pub const EASE_DECELERATE: (f32, f32, f32, f32) = (0.1, 0.9, 0.2, 1.0);
    /// `ui_tokens::motion::Easing::Accelerate.bezier()`.
    pub const EASE_ACCELERATE: (f32, f32, f32, f32) = (0.7, 0.0, 1.0, 0.5);
}

/// Elevation: drop shadows for layered surfaces (black at the given alpha).
pub mod elevation {
    /// One drop shadow: offsets and blur in DIPs, alpha in `[0.0, 1.0]`.
    #[derive(Clone, Copy, Debug, PartialEq)]
    pub struct Shadow {
        /// Horizontal offset in DIPs (positive = right).
        pub offset_x: f32,
        /// Vertical offset in DIPs (positive = down).
        pub offset_y: f32,
        /// Blur radius in DIPs.
        pub blur: f32,
        /// Alpha applied to the (always black) shadow colour.
        pub opacity: f32,
    }

    impl Shadow {
        /// A shadow from its four components.
        pub const fn new(offset_x: f32, offset_y: f32, blur: f32, opacity: f32) -> Self {
            Self {
                offset_x,
                offset_y,
                blur,
                opacity,
            }
        }
    }

    /// `ui_tokens::elevation::LEVEL_2`.
    pub const LEVEL_2: Shadow = Shadow::new(0.0, 1.0, 2.0, 0.1);
    /// `ui_tokens::elevation::LEVEL_4`.
    pub const LEVEL_4: Shadow = Shadow::new(0.0, 2.0, 4.0, 0.14);
    /// `ui_tokens::elevation::LEVEL_8`.
    pub const LEVEL_8: Shadow = Shadow::new(0.0, 4.0, 8.0, 0.16);
    /// `ui_tokens::elevation::LEVEL_16`.
    pub const LEVEL_16: Shadow = Shadow::new(0.0, 8.0, 16.0, 0.18);
    /// `ui_tokens::elevation::LEVEL_64`.
    pub const LEVEL_64: Shadow = Shadow::new(0.0, 32.0, 64.0, 0.22);
}

/// Corner radii, in DIPs.
pub mod radius {
    /// `ui_tokens::radius::CONTROL`.
    pub const CONTROL: f32 = 4.0;
    /// `ui_tokens::radius::CARD`.
    pub const CARD: f32 = 8.0;
    /// `ui_tokens::radius::BADGE`.
    pub const BADGE: f32 = 12.0;
}

/// The spacing scale, in DIPs, ascending.
pub mod spacing {
    /// `ui_tokens::spacing::SPACE_XXS`.
    pub const SPACE_XXS: f32 = 4.0;
    /// `ui_tokens::spacing::SPACE_XS`.
    pub const SPACE_XS: f32 = 8.0;
    /// `ui_tokens::spacing::SPACE_S`.
    pub const SPACE_S: f32 = 12.0;
    /// `ui_tokens::spacing::SPACE_M`.
    pub const SPACE_M: f32 = 16.0;
    /// `ui_tokens::spacing::SPACE_L`.
    pub const SPACE_L: f32 = 24.0;
    /// `ui_tokens::spacing::SPACE_XL`.
    pub const SPACE_XL: f32 = 32.0;
    /// `ui_tokens::spacing::SPACE_XXL`.
    pub const SPACE_XXL: f32 = 48.0;
    /// `ui_tokens::spacing::SPACE_XXXL`.
    pub const SPACE_XXXL: f32 = 64.0;
    /// `ui_tokens::spacing::SPACE_HUGE`.
    pub const SPACE_HUGE: f32 = 96.0;
}

/// Stroke widths (borders, dividers, rules), in DIPs.
pub mod stroke {
    /// `ui_tokens::stroke::HAIRLINE`.
    pub const HAIRLINE: f32 = 1.0;
    /// `ui_tokens::stroke::THIN`.
    pub const THIN: f32 = 2.0;
    /// `ui_tokens::stroke::ACCENT`.
    pub const ACCENT: f32 = 3.0;
    /// `ui_tokens::stroke::EMPHASIS`.
    pub const EMPHASIS: f32 = 4.0;
}

/// The type ramp: font sizes and their grid-aligned line heights, in DIPs.
pub mod typography {
    /// `ui_tokens::typography::SIZE_DISPLAY`.
    pub const SIZE_DISPLAY: f32 = 28.0;
    /// `ui_tokens::typography::SIZE_TITLE`.
    pub const SIZE_TITLE: f32 = 20.0;
    /// `ui_tokens::typography::SIZE_SUBTITLE`.
    pub const SIZE_SUBTITLE: f32 = 16.0;
    /// `ui_tokens::typography::SIZE_BODY`.
    pub const SIZE_BODY: f32 = 14.0;
    /// `ui_tokens::typography::SIZE_CAPTION`.
    pub const SIZE_CAPTION: f32 = 12.0;
    /// `ui_tokens::typography::SIZE_SMALL`.
    pub const SIZE_SMALL: f32 = 11.0;
    /// `ui_tokens::typography::LINE_DISPLAY`.
    pub const LINE_DISPLAY: f32 = 36.0;
    /// `ui_tokens::typography::LINE_TITLE`.
    pub const LINE_TITLE: f32 = 28.0;
    /// `ui_tokens::typography::LINE_SUBTITLE`.
    pub const LINE_SUBTITLE: f32 = 24.0;
    /// `ui_tokens::typography::LINE_BODY`.
    pub const LINE_BODY: f32 = 20.0;
    /// `ui_tokens::typography::LINE_CAPTION`.
    pub const LINE_CAPTION: f32 = 16.0;
    /// `ui_tokens::typography::LINE_SMALL`.
    pub const LINE_SMALL: f32 = 16.0;
}

/// Colours, as packed `0x00RRGGBB`.
pub mod color {
    /// `ui_tokens::color::STATUS_BLUE_FG`.
    pub const STATUS_BLUE_FG: u32 = 0x004578;

    /// The opinionated table hierarchy.
    pub mod table {
        /// `ui_tokens::color::table::HEADER`.
        pub const HEADER: u32 = 0x004578;
        /// `ui_tokens::color::table::HEADER_CONTENT`.
        pub const HEADER_CONTENT: u32 = 0xFFFFFF;
        /// `ui_tokens::color::table::FILTER`.
        pub const FILTER: u32 = 0xE5F1FB;
        /// `ui_tokens::color::table::FILTER_CONTENT`.
        pub const FILTER_CONTENT: u32 = 0x1A1A1A;
        /// `ui_tokens::color::table::GRID`.
        pub const GRID: u32 = 0xE0E0E0;
    }

    /// The shared dark form-control palette.
    pub mod dark {
        /// `ui_tokens::color::dark::TEXT_PRIMARY`.
        pub const TEXT_PRIMARY: u32 = 0xE6E6E6;
        /// `ui_tokens::color::dark::TEXT_SECONDARY`.
        pub const TEXT_SECONDARY: u32 = 0xADADAD;
        /// `ui_tokens::color::dark::TEXT_DISABLED`.
        pub const TEXT_DISABLED: u32 = 0x6A6A6A;
        /// `ui_tokens::color::dark::CARD_BG`.
        pub const CARD_BG: u32 = 0x1F1F1F;
        /// `ui_tokens::color::dark::CONTROL_REST`.
        pub const CONTROL_REST: u32 = 0x333333;
        /// `ui_tokens::color::dark::CONTROL_HOVER`.
        pub const CONTROL_HOVER: u32 = 0x3D3D3D;
        /// `ui_tokens::color::dark::CONTROL_PRESSED`.
        pub const CONTROL_PRESSED: u32 = 0x454545;
        /// `ui_tokens::color::dark::CONTROL_BORDER`.
        pub const CONTROL_BORDER: u32 = 0x484848;
        /// `ui_tokens::color::dark::CONTROL_BORDER_BOTTOM`.
        pub const CONTROL_BORDER_BOTTOM: u32 = 0x5A5A5A;
    }
}
