//! Host-projected evidence and actual execution provenance.

use super::model::{require_nonblank, unique_identities, validate_eligibility};
use super::*;
use crate::components::ClientCallGuidance;

/// An opaque evidence identity opened only by the authorized host.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AssistantEvidence {
    /// Stable source identity, never a model-authored navigation URL.
    pub id: String,
    /// Host-localized display name.
    pub label: String,
    /// Host-localized source category.
    pub source_kind: String,
    /// Accepted source revision.
    pub revision: u64,
    /// Host-localized freshness display.
    pub as_of: String,
    /// Explicit access verdict; unavailable sources are not implicitly openable.
    pub availability: AssistantAccess,
    /// Material limitations displayed beside this source.
    pub qualification: String,
}

/// How this accepted content was produced, independently of selected preference.
#[non_exhaustive]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ProvenanceMode {
    /// Newly generated by the actual engine recorded alongside it.
    Generated,
    /// Reused accepted content, not a new provider execution.
    CacheReuse,
    /// A human changed the accepted text.
    HumanEdited,
    /// Unrecognized provenance cannot establish execution claims.
    Unknown(String),
}

/// Actual execution metadata. Missing fields stay unknown in the presentation.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AssistantProvenance {
    /// Generated, reused or human-edited origin.
    pub mode: ProvenanceMode,
    /// Actual engine, never inferred from current settings.
    pub actual_engine: Option<String>,
    /// Actual model version when supplied.
    pub model_version: Option<String>,
    /// Accepted prompt version when supplied.
    pub prompt_version: Option<String>,
    /// Accepted skill version when supplied.
    pub skill_version: Option<String>,
    /// Actor-memory revisions actually supplied.
    pub memory_revisions: Vec<AssistantItemRevision>,
    /// Foundation revisions actually supplied.
    pub foundation_revisions: Vec<AssistantItemRevision>,
    /// Other source revisions actually supplied.
    pub supplied_sources: Vec<AssistantItemRevision>,
    /// Material omissions supplied by the host.
    pub omissions: Vec<String>,
    /// Host-localized build time.
    pub built_at: String,
}

/// A host-owned editable artifact, kept separate from the client destination.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AssistantArtifactDraft {
    /// Independently accepted text, not overwritten by an edit callback.
    pub accepted_text: String,
    /// Current host-controlled proposed text.
    pub proposed_text: String,
    /// Revision of the editable form.
    pub revision: u64,
    /// Explicit language label supplied by the host.
    pub language: String,
    /// A human changed the generated text; preserve that attribution.
    pub human_edited: bool,
    /// Host-supplied scalar-value bound.
    pub max_chars: usize,
}

/// A grounded beat preserves facts, missing detail and wording to avoid.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AssistantCallBeat {
    /// Stable identity for this ordered beat.
    pub id: String,
    /// Host-localized beat title.
    pub title: String,
    /// Communication objective.
    pub intent: String,
    /// Qualified fact, if one is actually available for this beat.
    pub fact: Option<AssistantFact>,
    /// Exact suggested wording, rendered as escaped text.
    pub say: String,
    /// Explicit wording or framing to avoid.
    pub avoid: Vec<String>,
    /// Named missing file detail when supplied.
    pub missing_fact: Option<String>,
    /// Optional host-supplied worked example.
    pub worked_example: Option<String>,
}

/// An attributed rehearsal turn, not an actual client conversation event.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AssistantRehearsalTurn {
    /// Display-only participant label supplied by the host.
    pub speaker: String,
    /// Hypothetical rehearsal text, not a sent message.
    pub text: String,
}

/// Rich call preparation reuses guidance data without owning a telephony engine.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AssistantCallPreparation {
    /// Existing controlled call-guidance contract; no private renderer extraction.
    pub guidance: ClientCallGuidance,
    /// Rich ordered beats supplementing the existing guidance projection.
    pub beats: Vec<AssistantCallBeat>,
    /// Explicit host-supplied framing hazards.
    pub framing_hazards: Vec<String>,
    /// Permitted ways to close this conversation.
    pub permitted_closes: Vec<String>,
    /// Qualified facts supplied for preparation.
    pub facts: Vec<AssistantFact>,
    /// Hypothetical consultant/client practice, never transcript history.
    pub rehearsal_turns: Vec<AssistantRehearsalTurn>,
    /// Optional SMS suggestion, never automatically inserted or sent.
    pub sms_suggestion: Option<String>,
    /// Optional proposed email subject.
    pub email_subject: Option<String>,
    /// Optional proposed email body.
    pub email_body: Option<String>,
    /// Explicit preparation language.
    pub language: String,
    /// Host confirmation of the language, independent of the selected preference.
    pub language_confirmed: bool,
    /// Known generation rubric version; absence remains unknown.
    pub rubric_version: Option<String>,
    /// Host-localized freshness explanation.
    pub freshness: String,
}

/// Business handoff vocabulary. No variant authorizes direct record mutation.
#[non_exhaustive]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum OwnerWorkflowKind {
    /// Prepare a note in the record owner's workflow.
    Note,
    /// Prepare an assignment for owner review.
    Assignment,
    /// Prepare a next action for owner review.
    NextAction,
    /// Prepare an escalation for owner review, not a notification.
    Escalation,
    /// Unsupported workflow kind cannot dispatch.
    Unknown(String),
}

/// The host's accepted destination draft and its reconciliation evidence.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AssistantDestination {
    /// Exact intended client identity.
    pub client_id: String,
    /// Exact existing client-thread identity.
    pub thread_id: String,
    /// Host-authorized channel identity.
    pub channel: String,
    /// Exact destination composer identity.
    pub draft_id: String,
    /// Expected accepted destination revision.
    pub draft_revision: u64,
    /// Current accepted destination content, never optimistically overwritten.
    pub current_text: String,
    /// Last accepted suggestion for byte-exact untouched-suggestion comparison.
    pub previous_suggestion: Option<String>,
    /// Host confirmation of this destination's current eligibility.
    pub eligibility: AssistantEligibility,
}

/// Closed destination families, preserving all expected record identities.
#[non_exhaustive]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ProposalTarget {
    /// Insert into an existing editable composer; never send.
    Composer(AssistantDestination),
    /// Open a specific owner workflow for review and confirmation.
    OwnerWorkflow {
        /// Typed workflow purpose.
        kind: OwnerWorkflowKind,
        /// Exact intended record identity.
        record_id: String,
        /// Expected accepted record revision.
        record_revision: u64,
        /// Exact workflow identity authorized by the host.
        owner_workflow_id: String,
        /// Host confirmation of target eligibility.
        eligibility: AssistantEligibility,
    },
    /// Unknown targets never emit an insertion or navigation command.
    Unknown(String),
}

/// Reviewed insertion semantics; none permit replacing a human-edited draft.
#[non_exhaustive]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum InsertionPolicy {
    /// Prepared openers require a genuinely empty destination.
    EmptyOnly,
    /// Replace only empty text or the exact unchanged preceding suggestion.
    EmptyOrUnchangedSuggestion,
    /// Open the owner workflow without claiming a write.
    OwnerWorkflow,
    /// Unsupported policy cannot authorize a handoff.
    Unknown(String),
}

/// Exact revision-bound proposal; review and insertion are independent requests.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AssistantProposal {
    /// Stable proposal identity.
    pub id: String,
    /// Current proposed content revision.
    pub revision: u64,
    /// Accepted source artifact or answer identity.
    pub source_id: String,
    /// Expected source revision.
    pub source_revision: u64,
    /// Current host-revalidated authority generations.
    pub context: AssistantContextStamp,
    /// Host-authoritative expiry in Unix milliseconds.
    pub expires_at_ms: u64,
    /// Exact accepted destination and expected revision.
    pub target: ProposalTarget,
    /// Reviewed plain-text suggestion, not an executed business command.
    pub content: String,
    /// Explicit owner-approved reconciliation policy.
    pub policy: InsertionPolicy,
    /// Exact proposal revision whose review was acknowledged by the host.
    pub reviewed_revision: Option<u64>,
    /// Current host eligibility of the whole proposal.
    pub eligibility: AssistantEligibility,
}

/// Artifact families have intentionally different presentation and action rules.
#[non_exhaustive]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ArtifactKind {
    /// Read-only conversation analysis with material limitations.
    Analysis {
        /// Host-supplied objections.
        objections: Vec<String>,
        /// Grounded talking points.
        talking_points: Vec<String>,
        /// Proposed next action, absent when not established.
        next_action: Option<String>,
        /// Material limits kept beside the analysis.
        limitations: Vec<String>,
    },
    /// A draft for a known recipient/channel, not a sent communication.
    ClientDraft {
        /// Display-safe recipient identity or description.
        recipient: String,
        /// Explicit host-authorized channel.
        channel: String,
        /// Requested language.
        language: String,
        /// Whether the host confirmed the language.
        language_confirmed: bool,
        /// Requested communication objective.
        intent: String,
        /// Optional subject for a supported channel.
        subject: Option<String>,
    },
    /// Exact approved opener identity; edited text cannot retain this identity.
    PreparedTemplate {
        /// Exact approved template identity.
        template_id: String,
        /// Exact accepted template revision.
        template_revision: u64,
        /// Host-authoritative template expiry.
        expires_at_ms: u64,
    },
    /// Rich call preparation, separate from manual call controls.
    CallPreparation(AssistantCallPreparation),
    /// Read-only factual briefing with explicit completeness.
    Briefing {
        /// Qualified facts, not an invented rating.
        facts: Vec<AssistantFact>,
        /// Host-localized completeness explanation.
        completeness: String,
    },
    /// Reviewable note/assignment/next-action/escalation handoff.
    WorkflowProposal {
        /// Exact intended owner target.
        target: ProposalTarget,
        /// Typed purpose, not a general action executor.
        kind: OwnerWorkflowKind,
    },
    /// Unsupported artifacts do not expose content or actions.
    Unknown(String),
}

/// A versioned artifact with independently owned edit and handoff projections.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AssistantArtifact {
    /// Stable accepted artifact identity.
    pub id: String,
    /// Accepted artifact revision.
    pub revision: u64,
    /// Host-revalidated context and authority generations.
    pub context: AssistantContextStamp,
    /// Current host permission to retain/use this artifact.
    pub eligibility: AssistantEligibility,
    /// Typed artifact presentation.
    pub kind: ArtifactKind,
    /// Actual generation/edit origin.
    pub provenance: AssistantProvenance,
    /// Individually qualified source identities.
    pub evidence: Vec<AssistantEvidence>,
    /// Absent for read-only analysis and briefing, not a fabricated empty draft.
    pub draft: Option<AssistantArtifactDraft>,
    /// Explicit reviewable handoff when the host supports one.
    pub proposal: Option<AssistantProposal>,
    /// Per-artifact grants, never inferred from content.
    pub capabilities: AssistantCapabilities,
}

/// Validates the artifact section without affecting unrelated conversation work.
pub fn validate_artifact(artifact: &AssistantArtifact) -> Result<(), AssistantContractError> {
    require_nonblank(&artifact.id)?;
    validate_context_stamp(&artifact.context)?;
    validate_eligibility(&artifact.eligibility)?;
    artifact.capabilities.validate()?;
    validate_provenance(&artifact.provenance)?;
    unique_identities(
        artifact
            .evidence
            .iter()
            .map(|evidence| evidence.id.as_str()),
    )?;
    for evidence in &artifact.evidence {
        validate_evidence(evidence)?;
    }
    if let Some(draft) = &artifact.draft {
        require_nonblank(&draft.language)?;
        if draft.accepted_text.chars().count() > draft.max_chars
            || draft.proposed_text.chars().count() > draft.max_chars
        {
            return Err(AssistantContractError::InvalidAnswer);
        }
    }
    if let Some(proposal) = &artifact.proposal {
        validate_proposal(proposal)?;
    }
    match &artifact.kind {
        ArtifactKind::Analysis {
            objections,
            talking_points,
            next_action,
            limitations,
        } => {
            if artifact.draft.is_some() {
                return Err(AssistantContractError::InvalidAnswer);
            }
            validate_display_list(objections)?;
            validate_display_list(talking_points)?;
            validate_display_list(limitations)?;
            validate_optional_display(next_action)
        }
        ArtifactKind::Briefing { completeness, .. } => {
            if artifact.draft.is_some() {
                return Err(AssistantContractError::InvalidAnswer);
            }
            require_nonblank(completeness)
        }
        ArtifactKind::ClientDraft {
            recipient,
            channel,
            language,
            intent,
            subject,
            ..
        } => {
            for value in [recipient, channel, language, intent] {
                require_nonblank(value)?;
            }
            validate_optional_display(subject)?;
            if artifact.draft.is_none() {
                return Err(AssistantContractError::InvalidAnswer);
            }
            Ok(())
        }
        ArtifactKind::PreparedTemplate { template_id, .. } => {
            require_nonblank(template_id)?;
            let Some(draft) = &artifact.draft else {
                return Err(AssistantContractError::InvalidAnswer);
            };
            require_nonblank(&draft.accepted_text)?;
            if draft.human_edited
                || draft.accepted_text != draft.proposed_text
                || artifact
                    .proposal
                    .as_ref()
                    .is_some_and(|proposal| proposal.policy != InsertionPolicy::EmptyOnly)
            {
                return Err(AssistantContractError::InvalidAnswer);
            }
            Ok(())
        }
        ArtifactKind::CallPreparation(preparation) => validate_call_preparation(preparation),
        ArtifactKind::WorkflowProposal { target, kind } => {
            validate_proposal_target(target)?;
            match target {
                ProposalTarget::OwnerWorkflow {
                    kind: target_kind, ..
                } if target_kind == kind => Ok(()),
                _ => Err(AssistantContractError::InvalidAnswer),
            }
        }
        ArtifactKind::Unknown(_) => Err(AssistantContractError::UnknownState),
    }
}

/// Validates a proposal's closed destination and insertion-policy shape.
pub fn validate_proposal(proposal: &AssistantProposal) -> Result<(), AssistantContractError> {
    require_nonblank(&proposal.id)?;
    require_nonblank(&proposal.source_id)?;
    require_nonblank(&proposal.content)?;
    validate_context_stamp(&proposal.context)?;
    validate_eligibility(&proposal.eligibility)?;
    validate_proposal_target(&proposal.target)?;
    match (&proposal.policy, &proposal.target) {
        (InsertionPolicy::Unknown(_), _) => Err(AssistantContractError::UnknownState),
        (
            InsertionPolicy::EmptyOnly | InsertionPolicy::EmptyOrUnchangedSuggestion,
            ProposalTarget::Composer(_),
        )
        | (InsertionPolicy::OwnerWorkflow, ProposalTarget::OwnerWorkflow { .. }) => Ok(()),
        _ => Err(AssistantContractError::InvalidAnswer),
    }
}

/// Checks snapshot-local source/context/review/expiry and embedded target shape.
///
/// This helper cannot establish current destination safety or grant a handoff.
/// Its destination text, revision and eligibility come only from the supplied
/// proposal snapshot, which may already be stale. The dispatcher must reread the
/// latest host state and check the current source identity, revision, content,
/// lifecycle, language and eligibility; current destination/record/workflow
/// identity, revision, content and eligibility; every applicable capability; and
/// pending or uncertain operations. Only the dispatcher's complete current-state
/// check can construct an actionable command. The host still revalidates it.
pub fn proposal_is_current(
    proposal: &AssistantProposal,
    source: &AssistantItemRevision,
    context: &AssistantContextStamp,
    now_ms: u64,
) -> bool {
    if validate_proposal(proposal).is_err()
        || proposal.source_id != source.id
        || proposal.source_revision != source.revision
        || proposal.context != *context
        || proposal.expires_at_ms <= now_ms
        || proposal.reviewed_revision != Some(proposal.revision)
        || proposal.eligibility != AssistantEligibility::Eligible
    {
        return false;
    }
    match (&proposal.target, &proposal.policy) {
        (ProposalTarget::Composer(destination), policy)
            if destination.eligibility == AssistantEligibility::Eligible =>
        {
            destination.current_text.is_empty()
                || (*policy == InsertionPolicy::EmptyOrUnchangedSuggestion
                    && destination.previous_suggestion.as_ref() == Some(&destination.current_text))
        }
        (ProposalTarget::OwnerWorkflow { eligibility, .. }, InsertionPolicy::OwnerWorkflow) => {
            *eligibility == AssistantEligibility::Eligible
        }
        _ => false,
    }
}

fn validate_proposal_target(target: &ProposalTarget) -> Result<(), AssistantContractError> {
    match target {
        ProposalTarget::Composer(destination) => {
            for identity in [
                &destination.client_id,
                &destination.thread_id,
                &destination.channel,
                &destination.draft_id,
            ] {
                require_nonblank(identity)?;
            }
            validate_optional_display(&destination.previous_suggestion)?;
            validate_eligibility(&destination.eligibility)
        }
        ProposalTarget::OwnerWorkflow {
            kind,
            record_id,
            owner_workflow_id,
            eligibility,
            ..
        } => {
            if matches!(kind, OwnerWorkflowKind::Unknown(_)) {
                return Err(AssistantContractError::UnknownState);
            }
            require_nonblank(record_id)?;
            require_nonblank(owner_workflow_id)?;
            validate_eligibility(eligibility)
        }
        ProposalTarget::Unknown(_) => Err(AssistantContractError::UnknownState),
    }
}

fn validate_call_preparation(
    preparation: &AssistantCallPreparation,
) -> Result<(), AssistantContractError> {
    require_nonblank(&preparation.language)?;
    require_nonblank(&preparation.freshness)?;
    unique_identities(
        preparation
            .guidance
            .beats
            .iter()
            .map(|beat| beat.id.as_str()),
    )?;
    for beat in &preparation.guidance.beats {
        require_nonblank(&beat.title)?;
        require_nonblank(&beat.say)?;
    }
    match &preparation.guidance.state {
        crate::components::ClientCallGuidanceState::Ready => {
            require_nonblank(&preparation.guidance.title)?;
            if preparation.guidance.body.trim().is_empty()
                && preparation.beats.is_empty()
                && preparation.guidance.beats.is_empty()
            {
                return Err(AssistantContractError::InvalidAnswer);
            }
        }
        crate::components::ClientCallGuidanceState::Failed { reason } => require_nonblank(reason)?,
        crate::components::ClientCallGuidanceState::Preparing { .. } => {}
    }
    unique_identities(preparation.beats.iter().map(|beat| beat.id.as_str()))?;
    for beat in &preparation.beats {
        for value in [&beat.title, &beat.intent, &beat.say] {
            require_nonblank(value)?;
        }
        validate_display_list(&beat.avoid)?;
        validate_optional_display(&beat.missing_fact)?;
        validate_optional_display(&beat.worked_example)?;
    }
    validate_display_list(&preparation.framing_hazards)?;
    validate_display_list(&preparation.permitted_closes)?;
    for turn in &preparation.rehearsal_turns {
        require_nonblank(&turn.speaker)?;
        require_nonblank(&turn.text)?;
    }
    for optional in [
        &preparation.sms_suggestion,
        &preparation.email_subject,
        &preparation.email_body,
        &preparation.rubric_version,
    ] {
        validate_optional_display(optional)?;
    }
    Ok(())
}

fn validate_optional_display(value: &Option<String>) -> Result<(), AssistantContractError> {
    value.as_deref().map_or(Ok(()), require_nonblank)
}

fn validate_display_list(values: &[String]) -> Result<(), AssistantContractError> {
    values.iter().try_for_each(|value| require_nonblank(value))
}
