//! `gen-tokens`' second output (ldui-3u3p): the token values `ldui-design`
//! needs, written as Rust into `crates/ldui-design/src/tokens/generated.rs`.
//!
//! `ldui-design` is consumed as a git dependency (4iiz-kit), where the
//! `../Rust-DeskApp/crates/ui-tokens` path does not exist, so it cannot depend
//! on `ui-tokens` the way this workspace's other crates do. Instead this
//! generator reads the real values here, where the sibling is available, and
//! commits them as literals. `gen-tokens --check` fails when the committed
//! file drifts, exactly as it does for `styles/tokens.css`.
//!
//! The `use ui_tokens::…` statements below are also what
//! `check-sibling-tokens` parses: this file replaced `src/tokens/preamble.rs`
//! as that guard's subject when the emitters moved into `ldui-design`, so
//! every item the generated file draws from must exist on the sibling's
//! default branch. Keep token references on lines of their own (never after
//! a `//` inside a string on the same line), so the guard's comment stripping
//! cannot hide them.

use ui_tokens::color;
use ui_tokens::elevation::{LEVEL_2, LEVEL_4, LEVEL_8, LEVEL_16, LEVEL_64, Shadow};
use ui_tokens::motion::{DURATION_FAST_MS, DURATION_NORMAL_MS, DURATION_SLOW_MS, Easing};
use ui_tokens::radius;
use ui_tokens::spacing::{
    SPACE_HUGE, SPACE_L, SPACE_M, SPACE_S, SPACE_XL, SPACE_XS, SPACE_XXL, SPACE_XXS, SPACE_XXXL,
};
use ui_tokens::stroke;
use ui_tokens::typography as ty;

/// Where the generated module lands, relative to the repo root.
pub(crate) const DESIGN_TOKENS_RS_PATH: &str = "crates/ldui-design/src/tokens/generated.rs";

/// The file's fixed preamble: its module doc.
const HEADER: &str = "\
//! Design-token values GENERATED by `cargo xtask gen-tokens` — do not edit
//! by hand.
//!
//! Source of truth: the `ui-tokens` crate shared with the Direct2D desktop
//! face in Rust-DeskApp. This crate never depends on it (it is consumed as a
//! git dependency, where that sibling path does not exist): the generator
//! reads the real values and writes them here, and `cargo xtask verify`
//! fails when this file drifts (`gen-tokens --check`). Edit the tokens
//! upstream, re-run the generator, and commit the result.
//!
//! Dimensions are DIPs (1 DIP = 1 CSS px at a 16px root); colours are packed
//! `0x00RRGGBB`.
";

/// The `Shadow` type the elevation constants are built from. Fixed text: it
/// mirrors `ui_tokens::elevation::Shadow` field for field, so the emitters'
/// formatting reads the same fields it always did.
const SHADOW_TYPE: &str =
    "    /// One drop shadow: offsets and blur in DIPs, alpha in `[0.0, 1.0]`.
    #[derive(Clone, Copy, Debug, PartialEq)]
    pub struct Shadow {
        /// Horizontal offset in DIPs (positive = right).
        pub offset_x: f32,
        /// Vertical offset in DIPs (positive = down).
        pub offset_y: f32,
        /// Blur radius in DIPs.
        pub blur: f32,
        /// Alpha applied to the (always black) shadow colour.
        pub opacity: f32,
    }

    impl Shadow {
        /// A shadow from its four components.
        pub const fn new(offset_x: f32, offset_y: f32, blur: f32, opacity: f32) -> Self {
            Self {
                offset_x,
                offset_y,
                blur,
                opacity,
            }
        }
    }
";

/// Render an `f32` as a Rust literal that round-trips exactly.
///
/// `Debug` prints the shortest representation that parses back to the same
/// bits and always keeps a decimal point (`4.0`, `0.33`), so the literal is a
/// valid `f32` and the emitters' `Display` formatting of it is unchanged.
fn f32_lit(v: f32) -> String {
    format!("{v:?}")
}

/// Render a packed colour as an upper-case `0x00RRGGBB` literal.
fn hex_lit(v: u32) -> String {
    format!("0x{v:06X}")
}

/// One elevation constant's declaration, built with `Shadow::new`.
fn shadow_decl(name: &str, s: Shadow) -> String {
    format!(
        "{name}: Shadow = Shadow::new({}, {}, {}, {})",
        f32_lit(s.offset_x),
        f32_lit(s.offset_y),
        f32_lit(s.blur),
        f32_lit(s.opacity)
    )
}

/// Emit one documented `pub const`, citing the `ui_tokens` item it copies.
fn konst(out: &mut String, indent: &str, source: &str, decl: &str) {
    out.push_str(&format!("{indent}/// `ui_tokens::{source}`.\n"));
    out.push_str(&format!("{indent}pub const {decl};\n"));
}

/// Emit a module of `f32` DIP constants.
fn f32_module(out: &mut String, doc: &str, module: &str, items: &[(&str, f32)]) {
    out.push_str(&format!("\n/// {doc}\npub mod {module} {{\n"));
    for (name, value) in items {
        let decl = format!("{name}: f32 = {}", f32_lit(*value));
        konst(out, "    ", &format!("{module}::{name}"), &decl);
    }
    out.push_str("}\n");
}

/// Emit a nested module of packed colours inside `color`.
fn hex_module(out: &mut String, doc: &str, module: &str, items: &[(&str, u32)]) {
    out.push_str(&format!("\n    /// {doc}\n    pub mod {module} {{\n"));
    for (name, value) in items {
        let decl = format!("{name}: u32 = {}", hex_lit(*value));
        konst(out, "        ", &format!("color::{module}::{name}"), &decl);
    }
    out.push_str("    }\n");
}

/// The Rust module `ldui-design` compiles as `tokens::generated`.
///
/// Pure, like [`crate::tokens_css`]: the drift check and the writer compare
/// the same bytes. The output is already rustfmt-canonical (and the module
/// is also declared `#[rustfmt::skip]`), so formatting never fights the
/// drift check.
pub(crate) fn design_tokens_rs() -> String {
    let mut out = String::with_capacity(8192);
    out.push_str(HEADER);

    // ---- motion ------------------------------------------------------------
    out.push_str(
        "\n/// Motion: durations in milliseconds, and easing curves as cubic-bezier\n/// control points `(x1, y1, x2, y2)`.\npub mod motion {\n",
    );
    let durations = [
        ("DURATION_FAST_MS", DURATION_FAST_MS),
        ("DURATION_NORMAL_MS", DURATION_NORMAL_MS),
        ("DURATION_SLOW_MS", DURATION_SLOW_MS),
    ];
    for (name, ms) in durations {
        konst(
            &mut out,
            "    ",
            &format!("motion::{name}"),
            &format!("{name}: u32 = {ms}"),
        );
    }
    let easings = [
        ("EASE_LINEAR", "Linear", Easing::Linear),
        ("EASE_STANDARD", "Standard", Easing::Standard),
        ("EASE_DECELERATE", "Decelerate", Easing::Decelerate),
        ("EASE_ACCELERATE", "Accelerate", Easing::Accelerate),
    ];
    for (name, variant, easing) in easings {
        let (x1, y1, x2, y2) = easing.bezier();
        let decl = format!(
            "{name}: (f32, f32, f32, f32) = ({}, {}, {}, {})",
            f32_lit(x1),
            f32_lit(y1),
            f32_lit(x2),
            f32_lit(y2)
        );
        konst(
            &mut out,
            "    ",
            &format!("motion::Easing::{variant}.bezier()"),
            &decl,
        );
    }
    out.push_str("}\n");

    // ---- elevation ---------------------------------------------------------
    out.push_str(
        "\n/// Elevation: drop shadows for layered surfaces (black at the given alpha).\npub mod elevation {\n",
    );
    out.push_str(SHADOW_TYPE);
    out.push('\n');
    let levels = [
        ("LEVEL_2", LEVEL_2),
        ("LEVEL_4", LEVEL_4),
        ("LEVEL_8", LEVEL_8),
        ("LEVEL_16", LEVEL_16),
        ("LEVEL_64", LEVEL_64),
    ];
    for (name, shadow) in levels {
        let decl = shadow_decl(name, shadow);
        konst(&mut out, "    ", &format!("elevation::{name}"), &decl);
    }
    out.push_str("}\n");

    // ---- dimensions --------------------------------------------------------
    let radii = [
        ("CONTROL", radius::CONTROL),
        ("CARD", radius::CARD),
        ("BADGE", radius::BADGE),
    ];
    f32_module(&mut out, "Corner radii, in DIPs.", "radius", &radii);

    let spacing = [
        ("SPACE_XXS", SPACE_XXS),
        ("SPACE_XS", SPACE_XS),
        ("SPACE_S", SPACE_S),
        ("SPACE_M", SPACE_M),
        ("SPACE_L", SPACE_L),
        ("SPACE_XL", SPACE_XL),
        ("SPACE_XXL", SPACE_XXL),
        ("SPACE_XXXL", SPACE_XXXL),
        ("SPACE_HUGE", SPACE_HUGE),
    ];
    f32_module(
        &mut out,
        "The spacing scale, in DIPs, ascending.",
        "spacing",
        &spacing,
    );

    let strokes = [
        ("HAIRLINE", stroke::HAIRLINE),
        ("THIN", stroke::THIN),
        ("ACCENT", stroke::ACCENT),
        ("EMPHASIS", stroke::EMPHASIS),
    ];
    f32_module(
        &mut out,
        "Stroke widths (borders, dividers, rules), in DIPs.",
        "stroke",
        &strokes,
    );

    let type_ramp = [
        ("SIZE_DISPLAY", ty::SIZE_DISPLAY),
        ("SIZE_TITLE", ty::SIZE_TITLE),
        ("SIZE_SUBTITLE", ty::SIZE_SUBTITLE),
        ("SIZE_BODY", ty::SIZE_BODY),
        ("SIZE_CAPTION", ty::SIZE_CAPTION),
        ("SIZE_SMALL", ty::SIZE_SMALL),
        ("LINE_DISPLAY", ty::LINE_DISPLAY),
        ("LINE_TITLE", ty::LINE_TITLE),
        ("LINE_SUBTITLE", ty::LINE_SUBTITLE),
        ("LINE_BODY", ty::LINE_BODY),
        ("LINE_CAPTION", ty::LINE_CAPTION),
        ("LINE_SMALL", ty::LINE_SMALL),
    ];
    f32_module(
        &mut out,
        "The type ramp: font sizes and their grid-aligned line heights, in DIPs.",
        "typography",
        &type_ramp,
    );

    // ---- colour ------------------------------------------------------------
    out.push_str("\n/// Colours, as packed `0x00RRGGBB`.\npub mod color {\n");
    let status_blue = hex_lit(color::STATUS_BLUE_FG);
    konst(
        &mut out,
        "    ",
        "color::STATUS_BLUE_FG",
        &format!("STATUS_BLUE_FG: u32 = {status_blue}"),
    );
    let table = [
        ("HEADER", color::table::HEADER),
        ("HEADER_CONTENT", color::table::HEADER_CONTENT),
        ("FILTER", color::table::FILTER),
        ("FILTER_CONTENT", color::table::FILTER_CONTENT),
        ("GRID", color::table::GRID),
    ];
    hex_module(
        &mut out,
        "The opinionated table hierarchy.",
        "table",
        &table,
    );
    let dark = [
        ("TEXT_PRIMARY", color::dark::TEXT_PRIMARY),
        ("TEXT_SECONDARY", color::dark::TEXT_SECONDARY),
        ("TEXT_DISABLED", color::dark::TEXT_DISABLED),
        ("CARD_BG", color::dark::CARD_BG),
        ("CONTROL_REST", color::dark::CONTROL_REST),
        ("CONTROL_HOVER", color::dark::CONTROL_HOVER),
        ("CONTROL_PRESSED", color::dark::CONTROL_PRESSED),
        ("CONTROL_BORDER", color::dark::CONTROL_BORDER),
        ("CONTROL_BORDER_BOTTOM", color::dark::CONTROL_BORDER_BOTTOM),
    ];
    hex_module(
        &mut out,
        "The shared dark form-control palette.",
        "dark",
        &dark,
    );
    out.push_str("}\n");

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{TokenRef, token_refs};

    fn tref(module: &str, symbol: Option<&str>) -> TokenRef {
        TokenRef {
            module: module.to_string(),
            symbol: symbol.map(|s| s.to_string()),
        }
    }

    #[test]
    fn f32_literals_round_trip_and_keep_a_decimal_point() {
        for v in [0.0f32, 0.1, 0.14, 0.33, 0.67, 4.0, 11.0, 9999.0] {
            let lit = f32_lit(v);
            assert!(lit.contains('.'), "{lit} is not an f32 literal");
            assert_eq!(lit.parse::<f32>().unwrap(), v, "{lit} does not round-trip");
        }
        assert_eq!(f32_lit(4.0), "4.0");
        assert_eq!(f32_lit(0.33), "0.33");
    }

    #[test]
    fn colour_literals_are_six_upper_case_hex_digits() {
        assert_eq!(hex_lit(0x004578), "0x004578");
        assert_eq!(hex_lit(0xE6E6E6), "0xE6E6E6");
    }

    /// The generated values are the live `ui_tokens` values, not a copy that
    /// happens to agree: each expected line is computed from the constant.
    #[test]
    fn generated_module_carries_the_live_token_values() {
        let rs = design_tokens_rs();
        for line in [
            format!("    pub const DURATION_FAST_MS: u32 = {DURATION_FAST_MS};\n"),
            format!("    pub const SPACE_XXS: f32 = {};\n", f32_lit(SPACE_XXS)),
            format!(
                "    pub const HAIRLINE: f32 = {};\n",
                f32_lit(stroke::HAIRLINE)
            ),
            format!(
                "    pub const LINE_BODY: f32 = {};\n",
                f32_lit(ty::LINE_BODY)
            ),
            format!("    pub const CARD: f32 = {};\n", f32_lit(radius::CARD)),
            format!(
                "        pub const TEXT_PRIMARY: u32 = {};\n",
                hex_lit(color::dark::TEXT_PRIMARY)
            ),
            format!(
                "        pub const GRID: u32 = {};\n",
                hex_lit(color::table::GRID)
            ),
        ] {
            assert!(rs.contains(&line), "missing {line:?} in:\n{rs}");
        }
        let (x1, y1, x2, y2) = Easing::Standard.bezier();
        let standard = format!(
            "    pub const EASE_STANDARD: (f32, f32, f32, f32) = ({}, {}, {}, {});\n",
            f32_lit(x1),
            f32_lit(y1),
            f32_lit(x2),
            f32_lit(y2)
        );
        assert!(rs.contains(&standard), "missing {standard:?}");
        let level_4 = format!("    pub const {};\n", shadow_decl("LEVEL_4", LEVEL_4));
        assert!(rs.contains(&level_4), "missing {level_4:?}");
    }

    /// Every public item is documented (ldui-design warns on missing docs)
    /// and every module the emitters import exists.
    #[test]
    fn generated_module_is_documented_and_complete() {
        let rs = design_tokens_rs();
        for module in [
            "pub mod motion {",
            "pub mod elevation {",
            "pub mod radius {",
            "pub mod spacing {",
            "pub mod stroke {",
            "pub mod typography {",
            "pub mod color {",
            "    pub mod table {",
            "    pub mod dark {",
        ] {
            assert_eq!(rs.matches(module).count(), 1, "{module}");
        }
        let lines: Vec<&str> = rs.lines().collect();
        for (i, line) in lines.iter().enumerate() {
            if line.trim_start().starts_with("pub const ") {
                assert!(
                    lines[i - 1].trim_start().starts_with("///"),
                    "undocumented: {line}"
                );
            }
        }
        assert!(rs.ends_with("}\n"));
    }

    /// `check-sibling-tokens` reads this file. Its parser must see the real
    /// references — including the `color::table`/`color::dark` modules
    /// reached through the bare `color` import — and no garbage module names.
    #[test]
    fn the_sibling_guard_parses_this_generator() {
        let refs = token_refs(include_str!("design_tokens.rs"));
        for want in [
            tref("motion", Some("DURATION_FAST_MS")),
            tref("motion", Some("Easing")),
            tref("elevation", Some("LEVEL_64")),
            tref("spacing", Some("SPACE_HUGE")),
            tref("stroke", Some("HAIRLINE")),
            tref("typography", Some("LINE_SMALL")),
            tref("radius", Some("BADGE")),
            tref("color", Some("STATUS_BLUE_FG")),
            tref("color", Some("table")),
            tref("color", Some("dark")),
        ] {
            assert!(refs.contains(&want), "guard does not see {want}");
        }
        for r in &refs {
            assert!(
                r.module.chars().all(|c| c.is_ascii_lowercase() || c == '_'),
                "unparseable module {r}"
            );
        }
    }
}
