use crate::core::ContentLayout;
use leptos::prelude::*;
use leptos_daisyui_rs::components::*;

/// Real-WASM regression fixture for ldui-1jxa: `Field` used to
/// `provide_context` a `FieldContext` onto whatever `Owner` was current when
/// it ran, which is the *shared* owner of every sibling built alongside it —
/// so a later, unrelated control that never wraps in its own `Field` (a
/// standalone `Input`/`Select`, or an `Input`/`Select` nested inside some
/// other component like `DatasetSelector` or an `EntityTable` column filter)
/// picked up the same `FieldContext` and rendered the *same* `id` as the
/// original `Field`'s own control. Chrome reports "Duplicate form field id in
/// the same form" for exactly this shape.
///
/// `doc/components/../../src/components/field/tests.rs` proves the owner
/// scoping natively (no DOM available there); this fixture proves the same
/// contract against real rendered ids: the `Field`-wrapped `Input` here mints
/// its own `ld-field-*` id, and the plain `Input`/`Select` that follow it —
/// deliberately *not* wrapped in a `Field` — must carry distinct ids of their
/// own (browser-default autogenerated ids, since neither supplies one) rather
/// than inheriting the `Field`'s id.
#[component]
pub fn FieldContextScopeDemo() -> impl IntoView {
    view! {
        <ContentLayout
            title="Field context scoping"
            description="Regression fixture for ldui-1jxa: a later standalone control must not inherit an earlier Field's id"
        >
            <div id="field-context-scope-fixture" class="flex flex-col gap-4 max-w-sm">
                <div data-testid="field-context-scope-field">
                    <Field label="Search office" help_text="Type to filter offices">
                        <Input attr:data-testid="field-context-scope-field-input" />
                    </Field>
                </div>

                <div data-testid="field-context-scope-standalone-input">
                    <label for="field-context-scope-standalone-input-control">
                        "Standalone input (no Field wrapper)"
                    </label>
                    <Input
                        attr:id="field-context-scope-standalone-input-control"
                        attr:data-testid="field-context-scope-standalone-input-control"
                    />
                </div>

                <div data-testid="field-context-scope-standalone-select">
                    <label for="field-context-scope-standalone-select-control">
                        "Standalone select (no Field wrapper)"
                    </label>
                    <Select attr:id="field-context-scope-standalone-select-control" attr:data-testid="field-context-scope-standalone-select-control">
                        <option value="mx">"Mexico City"</option>
                        <option value="in">"New Delhi"</option>
                    </Select>
                </div>

                <div data-testid="field-context-scope-bare-input">
                    // No caller-supplied id at all: proves the fix by ruling
                    // out the one case a caller-supplied id would mask --
                    // this control's id can only come from the browser's own
                    // default (empty) or from a leaked FieldContext.
                    <Input attr:data-testid="field-context-scope-bare-input-control" />
                </div>
            </div>
        </ContentLayout>
    }
}
